name: Build and upload release

on:
  push:
    branches:
      - 'feature/*'

jobs:
  build-release:
    runs-on: windows-2022
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - uses: ilammy/msvc-dev-cmd@v1
      - name: Build
        shell: cmd
        run: build.bat

      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          files: bin/studio-brightness.exe
          tag_name: 'feature'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
